### PR TITLE
fix Dropbox icon

### PR DESCRIPTION
**Pull request by Monirzadeh**
the last commit need more review, for example, Dropbox icon is not proper
you can change the icon with  for bigger font

### CODE REVIEW

**Comment by Monirzadeh** [comment]
I suggest check other formats for example sh

**Comment by alexanderjeurissen** [comment]
Can you elaborate on what you mean with 

> the last commit need more review, for example, Dropbox icon is not proper
you can change the icon with  for bigger font

I took a look at the changeset of this PR and it looks good, let me know if you need to make further changes or if you're good with this being merged in as is.

**Comment by Monirzadeh** [comment]
I commit some change that I found
Dropbox icon has two icons one of them is the smal size (in pull request) and other is large in comment
you merge which of them do you like
I prefer this icon    for my self

**Comment by alexanderjeurissen** [comment]
Ok merging as is, Thanks again for your contribution @Monirzadeh

**Pull request merged**
