### PR TITLE
Add more icons and config file names

### PR DESCRIPTION
**Pull request by j-degreef**
This commit add icons for movies and archives extensions. It add new configuration filenames too.
More of these may come in the future.
I hope everything is ok.

### CODE REVIEW

**Comment by j-degreef** [comment]
Yesterday version had a typo. If you want to merge my pull request, please use the latest commit.
BR,
Jerôme

**Comment by alexanderjeurissen** [comment]
@j-degreef Thanks for your PR, I'll review the changes this weekend !

**Comment by alexanderjeurissen** [comment]
@j-degreef is this PR finished as is ? if so then I'll merge it I like the changes !!!

**Comment by j-degreef** [comment]
Well, I was thinking about adding more archives extensions. I'll make a new commit with these and then it will be completed for now.
Should I make a new PR with the latest commit or just attach it here ?

**Comment by j-degreef** [comment]
@alexanderjeurissen 
Here's the latest commit.
While at it I couldn't resist to add a book icon for pdf and epub and a music icon for mp3, flac and ogg, beside archive extensions.
If everything is ok you can merge this one, I won't touch it anymore.

If I think about more extensions I'll make a list and commit the changes at once in the future.

**Comment by j-degreef** [comment]
@alexanderjeurissen
Here's the latest commit.
While at it I couldn't resist to add a book icon for pdf and epub and a music icon for mp3, flac and ogg, beside archive extensions.
If everything is ok you can merge this one, I won't touch it anymore.

If I think about more extensions I'll make a list and commit the changes at once in the future.

**Comment by alexanderjeurissen** [comment]
@j-degreef thanks again for your contribution. If you come up with more extensions let me know !!

**Comment by j-degreef** [comment]
@alexanderjeurissen 
Thanks for merging my branch.
I'll let you know if I have more ideas.

**Pull request merged**
