### PR TITLE
fix: replace deprecated Nerd Font icons with new ones

### PR DESCRIPTION
**Pull request by prateekpunetha**
The previous icons in [devicons.py](git@github.com:prateekpunetha/ranger_devicons.git) were deprecated, so I replaced them with new ones to ensure compatibility and maintain consistency.

### CODE REVIEW

**Comment by alexanderjeurissen** [comment]
Hi @prateekpunetha 

Thank you so much for your contribution.

I just merged in https://github.com/alexanderjeurissen/ranger_devicons/pull/115 which aims to solve the same issue. 
Can you check if your PR is still necessary when looking at the latest main branch ? and if so can you resolve the merge conflicts ?

thanks 🙏

**Comment by prateekpunetha** [comment]
Thank you for merging #115. I noticed that it addresses the same issue as my PR. I have updated my PR #113 to include [appropriate icons](https://github.com/alexanderjeurissen/ranger_devicons/pull/113/files) for the PDF and R icon. Could you review the updated changes and consider merging them?. Let me know if there are any further changes I can make. Thank you.

**Comment by Tokariew** [comment]
I would say: please merge this PR, for the nice pdf/R icon
currently R files have ruby icon and not rlang one
And pdf use some generic file one

**Comment by alexanderjeurissen** [comment]
Thx for updating the PR 🙇‍♂️

**Pull request merged**
